import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";
import { UserCourseListContextProvider } from "./_context/UserCourseListContext";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Course GenX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>AI Course GenX</title>
        <meta name="description" content="AI Course GenX" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <ClerkProvider>
    <UserCourseListContextProvider>
      <GoogleOneTap/>
      <body className={inter.className}>{children}</body>
    </UserCourseListContextProvider>
    </ClerkProvider>
    </html>
  );
}
